{
    imports = [
        ./cloud
        ./languages
        ./scripts
        ./alacritty.nix
        ./fonts.nix
        ./gnumake.nix
        ./gpg.nix
        ./libreoffice.nix
        ./neovim.nix
        ./ollama.nix
        ./qbittorrent.nix
        ./signal.nix
        ./ssh.nix
        ./sway.nix
        ./tmux.nix
        ./vlc.nix
        ./yazi.nix
        ./zsh.nix
    ];
}
