on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

env:
  PR_BASE_BRANCH: main
  PR_BRANCH: update-flake-lock

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: cachix/install-nix-action@v30

      - name: Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch -c $PR_BRANCH

      - name: Update flake.lock
        run: nix flake update

      - name: Commit changes
        run: |
          (git add flake.lock \
          && git diff --staged --quiet) \
          || git commit -m "chore(nix): update \`flake.lock\`"

      - name: Push changes
        run: git push -u origin $PR_BRANCH

      - name: Create PR
        run: >
          gh pr create --title "chore(nix): update \`flake.lock\`" --body "Update \`flake.lock\`" --base $PR_BASE_BRANCH --assignee waduhek
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
