on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

permissions:
  pull-requests: write

env:
  PR_BASE_BRANCH: nixos-setup

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: cachix/install-nix-action@v30

      - name: Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch -c update-flake-lock

      - name: Update flake.lock
        run: nix flake update

      - name: Commit changes
        run: |
          (git add flake.lock \
          && git diff --staged --quiet) \
          || git commit -m "chore(nix): update \`flake.lock\`"

      - name: Create PR
        run: gh pr create --fill --base $PR_BASE_BRANCH
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
